// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUll51Tihp6WojL_hwWz8Ffdwr5EruH9E',
    appId: '1:525963188971:web:87403baf9830c26dd33cae',
    messagingSenderId: '525963188971',
    projectId: 'spendpal-app-blrtechpub',
    authDomain: 'spendpal-app-blrtechpub.firebaseapp.com',
    storageBucket: 'spendpal-app-blrtechpub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2V5oOMa71uogBS2VMBi8xnu_bh2I6QcQ',
    appId: '1:525963188971:android:d2f44db944c605d2d33cae',
    messagingSenderId: '525963188971',
    projectId: 'spendpal-app-blrtechpub',
    storageBucket: 'spendpal-app-blrtechpub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_hlfs8TkYfjloyAV0UPVjWmk4KIwV61g',
    appId: '1:525963188971:ios:db3412dbf4ed85d9d33cae',
    messagingSenderId: '525963188971',
    projectId: 'spendpal-app-blrtechpub',
    storageBucket: 'spendpal-app-blrtechpub.firebasestorage.app',
    iosBundleId: 'com.example.spendpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_hlfs8TkYfjloyAV0UPVjWmk4KIwV61g',
    appId: '1:525963188971:ios:db3412dbf4ed85d9d33cae',
    messagingSenderId: '525963188971',
    projectId: 'spendpal-app-blrtechpub',
    storageBucket: 'spendpal-app-blrtechpub.firebasestorage.app',
    iosBundleId: 'com.example.spendpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUll51Tihp6WojL_hwWz8Ffdwr5EruH9E',
    appId: '1:525963188971:web:42e03d10272a4adfd33cae',
    messagingSenderId: '525963188971',
    projectId: 'spendpal-app-blrtechpub',
    authDomain: 'spendpal-app-blrtechpub.firebaseapp.com',
    storageBucket: 'spendpal-app-blrtechpub.firebasestorage.app',
  );
}
